#!/bin/sh
cdiff() { (R=$(printf '\033\[31m');G=$(printf '\033\[32m');B=$(printf '\033\[36m');W=$(printf '\033\[1m');N=$(printf '\033\[0m');diff -u "$@"|sed "s/^\(@@..*@@\)$/$B\1$N/g;s/^\(+.*\)$/$G\1$N/g;s/^\(-.*\)$/$R\1$N/g;s/^$G\(+++ [^ ].*\)/$W\1/g;s/^$R\(--- [^ ].*\)/$W\1/g;")}
cdiff "$@"
